//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('grades')
export class gradesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('real', { nullable: true })
  cgpa: number;

  @Column('text', { nullable: true })
  gradeCalculator: string;
}
