//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('HealthAndMentalCare')
export class HealthAndMentalCareEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  serviceName: string;

  @Column('text', { nullable: true })
  description: string;

  @Column('text', { nullable: true })
  contactInformation: string;

  @Column('text', { nullable: true })
  availability: string;
}
