//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('LoanCalculator')
export class LoanCalculatorEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('real', { nullable: true })
  loanAmount: number;

  @Column('real', { nullable: true })
  interestRate: number;

  @Column('integer', { nullable: true })
  loanTerm: number;
}
