//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    JobsAndInternships: {
      name: 'Jobs And Internships',
      fields: {
        title: 'Title',
        description: 'Description',
        company: 'Company',
        location: 'Location',
        applicationDeadline: 'Application Deadline',
        type: 'Type',
        id: 'id',
      },
    },
    grades: {
      name: 'Grades',
      fields: { cgpa: 'Cgpa', gradeCalculator: 'Grade Calculator', id: 'id' },
    },
    subjects: {
      name: 'Subjects',
      fields: { subjectName: 'Subject Name', id: 'id' },
    },
    notes: {
      name: 'Notes',
      fields: {
        title: 'Title',
        content: 'Content',
        subject: 'Subject',
        dateCreated: 'Date Created',
        id: 'id',
      },
    },
    HealthAndMentalCare: {
      name: 'Health And Mental Care',
      fields: {
        serviceName: 'Service Name',
        description: 'Description',
        contactInformation: 'Contact Information',
        availability: 'Availability',
        id: 'id',
      },
    },
    news: {
      name: 'News',
      fields: {
        title: 'Title',
        content: 'Content',
        datePublished: 'Date Published',
        category: 'Category',
        id: 'id',
      },
    },
    LoanCalculator: {
      name: 'Loan Calculator',
      fields: {
        loanAmount: 'Loan Amount',
        interestRate: 'Interest Rate',
        loanTerm: 'Loan Term',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    JobsAndInternships: {
      name: 'Jobs And Internships (fr)',
      fields: {
        title: 'Title (fr)',
        description: 'Description (fr)',
        company: 'Company (fr)',
        location: 'Location (fr)',
        applicationDeadline: 'Application Deadline (fr)',
        type: 'Type (fr)',
        id: 'id',
      },
    },
    grades: {
      name: 'Grades (fr)',
      fields: {
        cgpa: 'Cgpa (fr)',
        gradeCalculator: 'Grade Calculator (fr)',
        id: 'id',
      },
    },
    subjects: {
      name: 'Subjects (fr)',
      fields: { subjectName: 'Subject Name (fr)', id: 'id' },
    },
    notes: {
      name: 'Notes (fr)',
      fields: {
        title: 'Title (fr)',
        content: 'Content (fr)',
        subject: 'Subject (fr)',
        dateCreated: 'Date Created (fr)',
        id: 'id',
      },
    },
    HealthAndMentalCare: {
      name: 'Health And Mental Care (fr)',
      fields: {
        serviceName: 'Service Name (fr)',
        description: 'Description (fr)',
        contactInformation: 'Contact Information (fr)',
        availability: 'Availability (fr)',
        id: 'id',
      },
    },
    news: {
      name: 'News (fr)',
      fields: {
        title: 'Title (fr)',
        content: 'Content (fr)',
        datePublished: 'Date Published (fr)',
        category: 'Category (fr)',
        id: 'id',
      },
    },
    LoanCalculator: {
      name: 'Loan Calculator (fr)',
      fields: {
        loanAmount: 'Loan Amount (fr)',
        interestRate: 'Interest Rate (fr)',
        loanTerm: 'Loan Term (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
